---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/component: controller
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/component: controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: digital-identity-check
  labels:
    app: digital-identity-check
spec:
  selector:
    matchLabels:
      app: digital-identity-check
  template:
    metadata:
      labels:
        app: digital-identity-check
    spec:
      containers:
        - name: digital-identity-check
          image: digital-identity-check
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: service-digital-identity-check
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: digital-identity-check
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-digital-identity-check
spec:
  rules:
    - host: digital-identity-check.localdev
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: service-digital-identity-check
                port:
                  number: 80
